# Generated by Django 4.2.2 on 2023-06-09 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='qa_app.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
